/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class MangInasag_menu_page extends javax.swing.JFrame {

    public MangInasag_menu_page() {
        initComponents();
     
        //btn_PH1.setText("<html>Chicken Inasal<br>& Pork BBQ Family Fiesta</center></html>");
        //btn_PH1.setFont(new Font("Segoe UI", Font.BOLD, 12));
        //btn_PH1.setPreferredSize(new Dimension(100, 60));
          
        
        btn_PM1.setText("<html>Paa Large - PM1<br>₱ 149.00</html>");
        //btn_PH1.setFont(new Font("Segoe UI", Font.BOLD, 12));
        //btn_PH1.setPreferredSize(new Dimension(100, 60));
    }
    
    public class DBConnection {
    private static final String URL = "jdbc:mysql://localhost:3306/foodmenu";
    private static final String USER = "root"; // change if your username is different
    private static final String PASSWORD = ""; // add password if you have one

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header_color = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_menu = new javax.swing.JPanel();
        pnl_tab = new javax.swing.JTabbedPane();
        pnl_menupage = new javax.swing.JPanel();
        btn_HaloHalo = new javax.swing.JButton();
        btn_CHaloHalo = new javax.swing.JButton();
        pn9 = new javax.swing.JSpinner();
        pn10 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_PM2 = new javax.swing.JButton();
        btn_PM1 = new javax.swing.JButton();
        btn_TSPechoLarge = new javax.swing.JButton();
        btn_Inasal = new javax.swing.JButton();
        btn_TSPaaLarge = new javax.swing.JButton();
        btn_Fiesta = new javax.swing.JButton();
        btn_PorkSisig = new javax.swing.JButton();
        btn_Bangus = new javax.swing.JButton();
        pn1 = new javax.swing.JSpinner();
        pn2 = new javax.swing.JSpinner();
        pn3 = new javax.swing.JSpinner();
        pn4 = new javax.swing.JSpinner();
        pn5 = new javax.swing.JSpinner();
        pn6 = new javax.swing.JSpinner();
        pn7 = new javax.swing.JSpinner();
        pn8 = new javax.swing.JSpinner();
        lblimage1 = new javax.swing.JLabel();
        lblimage2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnl_transaction = new javax.swing.JPanel();
        txt_order = new javax.swing.JLabel();
        btn_clear_orders = new javax.swing.JButton();
        pnl_orders = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRec = new javax.swing.JTextArea();
        txt_total = new javax.swing.JLabel();
        txt_total_cash = new javax.swing.JTextField();
        btn_PlaceOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_header_color.setBackground(new java.awt.Color(45, 151, 81));
        pnl_header_color.setForeground(new java.awt.Color(45, 151, 81));
        pnl_header_color.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mang Inasag/logo.jpeg"))); // NOI18N
        pnl_header_color.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 23, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        pnl_header_color.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 22, -1, -1));

        getContentPane().add(pnl_header_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 130));

        pnl_menu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_tab.setBackground(new java.awt.Color(45, 151, 81));
        pnl_tab.setForeground(new java.awt.Color(255, 255, 255));
        pnl_tab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        pnl_menupage.setBackground(new java.awt.Color(255, 255, 255));

        btn_HaloHalo.setBackground(new java.awt.Color(45, 151, 81));
        btn_HaloHalo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_HaloHalo.setForeground(new java.awt.Color(255, 255, 255));
        btn_HaloHalo.setText("Extra Creamy Halo-Halo");
        btn_HaloHalo.setMaximumSize(new java.awt.Dimension(168, 32));
        btn_HaloHalo.setMinimumSize(new java.awt.Dimension(168, 32));
        btn_HaloHalo.setPreferredSize(new java.awt.Dimension(168, 32));
        btn_HaloHalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HaloHaloActionPerformed(evt);
            }
        });

        btn_CHaloHalo.setBackground(new java.awt.Color(45, 151, 81));
        btn_CHaloHalo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CHaloHalo.setForeground(new java.awt.Color(255, 255, 255));
        btn_CHaloHalo.setText("Creama de Leche Halo-Halo");
        btn_CHaloHalo.setMaximumSize(new java.awt.Dimension(168, 32));
        btn_CHaloHalo.setMinimumSize(new java.awt.Dimension(168, 32));
        btn_CHaloHalo.setPreferredSize(new java.awt.Dimension(168, 32));
        btn_CHaloHalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CHaloHaloActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mang Inasag/menu_img/Extra-Creamy-Halo-Halo.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mang Inasag/menu_img/Crema-de-Leche-Small.png"))); // NOI18N

        javax.swing.GroupLayout pnl_menupageLayout = new javax.swing.GroupLayout(pnl_menupage);
        pnl_menupage.setLayout(pnl_menupageLayout);
        pnl_menupageLayout.setHorizontalGroup(
            pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menupageLayout.createSequentialGroup()
                .addGroup(pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_menupageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_menupageLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_HaloHalo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_menupageLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(165, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_menupageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_CHaloHalo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(185, 185, 185))))
        );
        pnl_menupageLayout.setVerticalGroup(
            pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menupageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_menupageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CHaloHalo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HaloHalo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_menupageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pnl_tab.addTab("DESSERTS", pnl_menupage);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_PM2.setBackground(new java.awt.Color(45, 151, 81));
        btn_PM2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_PM2.setForeground(new java.awt.Color(255, 255, 255));
        btn_PM2.setText("Pecho Large - PM2");
        btn_PM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PM2ActionPerformed(evt);
            }
        });

        btn_PM1.setBackground(new java.awt.Color(45, 151, 81));
        btn_PM1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_PM1.setForeground(new java.awt.Color(255, 255, 255));
        btn_PM1.setText("Paa Large - PM1");
        btn_PM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PM1ActionPerformed(evt);
            }
        });

        btn_TSPechoLarge.setBackground(new java.awt.Color(45, 151, 81));
        btn_TSPechoLarge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TSPechoLarge.setForeground(new java.awt.Color(255, 255, 255));
        btn_TSPechoLarge.setText("Todo Solb Pecho Large");
        btn_TSPechoLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TSPechoLargeActionPerformed(evt);
            }
        });

        btn_Inasal.setBackground(new java.awt.Color(45, 151, 81));
        btn_Inasal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Inasal.setForeground(new java.awt.Color(255, 255, 255));
        btn_Inasal.setText("Chicken Inasal Regular");
        btn_Inasal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InasalActionPerformed(evt);
            }
        });

        btn_TSPaaLarge.setBackground(new java.awt.Color(45, 151, 81));
        btn_TSPaaLarge.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_TSPaaLarge.setForeground(new java.awt.Color(255, 255, 255));
        btn_TSPaaLarge.setText("Todo Solb Paa Large");
        btn_TSPaaLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TSPaaLargeActionPerformed(evt);
            }
        });

        btn_Fiesta.setBackground(new java.awt.Color(45, 151, 81));
        btn_Fiesta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Fiesta.setForeground(new java.awt.Color(255, 255, 255));
        btn_Fiesta.setText("Fiesta Meal");
        btn_Fiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FiestaActionPerformed(evt);
            }
        });

        btn_PorkSisig.setBackground(new java.awt.Color(45, 151, 81));
        btn_PorkSisig.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_PorkSisig.setForeground(new java.awt.Color(255, 255, 255));
        btn_PorkSisig.setText("Pork Sisig");
        btn_PorkSisig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PorkSisigActionPerformed(evt);
            }
        });

        btn_Bangus.setBackground(new java.awt.Color(45, 151, 81));
        btn_Bangus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Bangus.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bangus.setText("Bangus Sisig");
        btn_Bangus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BangusActionPerformed(evt);
            }
        });

        lblimage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mang Inasag/menu_img/Paa Large (PM1).png"))); // NOI18N

        lblimage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mang Inasag/menu_img/TodoSolbPechoLarge.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mang Inasag/menu_img/TodoSolbPaaLarge.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mang Inasag/menu_img/PorkSisig.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_PM1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_TSPechoLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Inasal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Fiesta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Bangus, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_PM2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_TSPaaLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_PorkSisig, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(lblimage2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_PM2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TSPaaLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_PorkSisig, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_PM1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Inasal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Fiesta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Bangus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_TSPechoLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        pnl_tab.addTab("RICE MEALS", jPanel1);

        pnl_menu.add(pnl_tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 920, 540));

        txt_order.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_order.setText("Current Order");

        btn_clear_orders.setBackground(new java.awt.Color(254, 220, 11));
        btn_clear_orders.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_clear_orders.setForeground(new java.awt.Color(0, 0, 0));
        btn_clear_orders.setText("CLEAR");

        pnl_orders.setBackground(new java.awt.Color(255, 255, 255));

        txaRec.setColumns(20);
        txaRec.setRows(5);
        jScrollPane1.setViewportView(txaRec);

        javax.swing.GroupLayout pnl_ordersLayout = new javax.swing.GroupLayout(pnl_orders);
        pnl_orders.setLayout(pnl_ordersLayout);
        pnl_ordersLayout.setHorizontalGroup(
            pnl_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ordersLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnl_ordersLayout.setVerticalGroup(
            pnl_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ordersLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_total.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_total.setText("Total: ");

        txt_total_cash.setEditable(false);
        txt_total_cash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_total_cash.setForeground(new java.awt.Color(45, 151, 81));
        txt_total_cash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total_cash.setText("₱0.00");
        txt_total_cash.setBorder(null);
        txt_total_cash.setEnabled(false);

        btn_PlaceOrder.setBackground(new java.awt.Color(0, 0, 0));
        btn_PlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_PlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btn_PlaceOrder.setText("PLACE ORDER");
        btn_PlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_transactionLayout = new javax.swing.GroupLayout(pnl_transaction);
        pnl_transaction.setLayout(pnl_transactionLayout);
        pnl_transactionLayout.setHorizontalGroup(
            pnl_transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_transactionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnl_transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_transactionLayout.createSequentialGroup()
                        .addComponent(txt_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_total_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_PlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_orders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_transactionLayout.createSequentialGroup()
                        .addComponent(txt_order, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_clear_orders)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        pnl_transactionLayout.setVerticalGroup(
            pnl_transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_transactionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_order, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total_cash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_PlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnl_menu.add(pnl_transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 340, 600));

        getContentPane().add(pnl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1320, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PM1ActionPerformed
     
     int value = Integer.parseInt(pn1.getValue().toString());
      if (value > 10){
          JOptionPane.showMessageDialog(rootPane, "Invalid");
          System.out.println("babaan mo naman ung quantity pre");  
        }else{
        String PN1 = pn1.getValue().toString();
        
        txaRec.setText("PM1 Quantity: " + PN1);
    }//GEN-LAST:event_btn_PM1ActionPerformed
    }
    private void btn_TSPechoLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TSPechoLargeActionPerformed
       // MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
          int value = Integer.parseInt(pn5.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }
    }//GEN-LAST:event_btn_TSPechoLargeActionPerformed

    private void btn_InasalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InasalActionPerformed
        //MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
        int value = Integer.parseInt(pn6.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }
    }//GEN-LAST:event_btn_InasalActionPerformed

    private void btn_TSPaaLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TSPaaLargeActionPerformed
        //MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
         int value = Integer.parseInt(pn4.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }
    }//GEN-LAST:event_btn_TSPaaLargeActionPerformed

    private void btn_FiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FiestaActionPerformed
        //MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
        int value = Integer.parseInt(pn7.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }
    }//GEN-LAST:event_btn_FiestaActionPerformed

    private void btn_PorkSisigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PorkSisigActionPerformed
        //MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
        int value = Integer.parseInt(pn4.getValue().toString());
      if (value > 10){
          JOptionPane.showMessageDialog(rootPane, "Invalid"); 
        }else{
        String PN1 = pn4.getValue().toString();
        
        txaRec.setText("PSisig Quantity: " + PN1);
    }                                       
    }//GEN-LAST:event_btn_PorkSisigActionPerformed

    private void btn_BangusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BangusActionPerformed
        //MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
        int value = Integer.parseInt(pn8.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }
    }//GEN-LAST:event_btn_BangusActionPerformed

    private void btn_PlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlaceOrderActionPerformed
        
    }//GEN-LAST:event_btn_PlaceOrderActionPerformed

    private void btn_PM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PM2ActionPerformed
      // MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
        int value = Integer.parseInt(pn2.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }          
    }//GEN-LAST:event_btn_PM2ActionPerformed

    private void btn_HaloHaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HaloHaloActionPerformed
       //MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
         int value = Integer.parseInt(pn9.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }
    }//GEN-LAST:event_btn_HaloHaloActionPerformed

    private void btn_CHaloHaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CHaloHaloActionPerformed
        //MangInasag_Quantity qp = new MangInasag_Quantity();
        //qp.setVisible(true);
         int value = Integer.parseInt(pn10.getValue().toString());

    if (value > 10) {
        JOptionPane.showMessageDialog(rootPane, "Invalid. Maximum allowed quantity is 10.");
    } else {
        txaRec.append("TS Pecho L Quantity: " + value + "\n");
    }
    }//GEN-LAST:event_btn_CHaloHaloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MangInasag_menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MangInasag_menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MangInasag_menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MangInasag_menu_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MangInasag_menu_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bangus;
    private javax.swing.JButton btn_CHaloHalo;
    private javax.swing.JButton btn_Fiesta;
    private javax.swing.JButton btn_HaloHalo;
    private javax.swing.JButton btn_Inasal;
    private javax.swing.JButton btn_PM1;
    private javax.swing.JButton btn_PM2;
    private javax.swing.JButton btn_PlaceOrder;
    private javax.swing.JButton btn_PorkSisig;
    private javax.swing.JButton btn_TSPaaLarge;
    private javax.swing.JButton btn_TSPechoLarge;
    private javax.swing.JButton btn_clear_orders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lblimage1;
    private javax.swing.JLabel lblimage2;
    private javax.swing.JSpinner pn1;
    private javax.swing.JSpinner pn10;
    private javax.swing.JSpinner pn2;
    private javax.swing.JSpinner pn3;
    private javax.swing.JSpinner pn4;
    private javax.swing.JSpinner pn5;
    private javax.swing.JSpinner pn6;
    private javax.swing.JSpinner pn7;
    private javax.swing.JSpinner pn8;
    private javax.swing.JSpinner pn9;
    private javax.swing.JPanel pnl_header_color;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_menupage;
    private javax.swing.JPanel pnl_orders;
    private javax.swing.JTabbedPane pnl_tab;
    private javax.swing.JPanel pnl_transaction;
    private javax.swing.JTextArea txaRec;
    private javax.swing.JLabel txt_order;
    private javax.swing.JLabel txt_total;
    private javax.swing.JTextField txt_total_cash;
    // End of variables declaration//GEN-END:variables
}

